### ISSUE TITLE
Create a job in Travis to run test whitout need create a pull request

### ISSUE THREAD

**Issue by nestornav** [pumascript/puma#94] opened 2017-08-23 22:57 UTC

**Comment by Undre4m** [comment] 2017-10-19 23:43
_Needs Info._ Travis runs CI procedure whenever a commit is pushed to the repo, or a forked project elevates a PR for merging.
>**Important note**
CI **only runs** on the main repo as it's so configured. **NOT** on forked projects as they need individual configuration as far as i'm aware.

Since CI seems to work as intended i'll close this issue until further information is provided.

**Closed by Undre4m** 2017-10-19 23:43 UTC
Labels: enhancement, testing
